import AsyncStorage from '@react-native-async-storage/async-storage';
import {useNavigation} from '@react-navigation/native';
import {userFakeData} from '@src/globals/constants/fakeData';
import {buttonActionInitialState} from '@src/globals/constants/login';
import {config} from '@src/hooks/config/config';
import {getConfigurationFirebase} from '@src/hooks/firebase/config/config';
import {geUserByPhoneNumberFirebase} from '@src/hooks/firebase/user/user';
import {getLocation} from '@src/hooks/locations/geocoderHook';
import {setGroupQuery, updateGroupQuery} from '@src/reactQuery/groupsQuery';
import {Configuration} from '@src/types/configuration';
import {RegisterType, StackNavigation} from '@src/types/globalTypes';
import {Group} from '@src/types/groups';
import {ResultLocations} from '@src/types/locationTypes';
import {LoginFormAction} from '@src/types/loginTypes';
import {DataKey, User} from '@src/types/userTypes';
import {t} from 'i18next';
import {useEffect, useState} from 'react';
import {Platform} from 'react-native';

const adminFormHook = (type: RegisterType) => {
  const os = Platform.OS;
  const navigation = useNavigation<StackNavigation>();
  const [myCurrentLocation, setMyCurrentLocation] = useState<ResultLocations>();
  const [alertGroupFound, setAlertGroupFound] = useState(false);
  const [groupFound, setGroupFound] = useState(false);
  const [user, setUser] = useState<User>();
  const configuration = config({user});
  const [alertUserExist, setAlertUserExist] = useState(false);
  const [tokenPush, setTokenPush] = useState<string>();
  const [currentButtonAction, setCurrentButtonAction] =
    useState<LoginFormAction>(buttonActionInitialState);
  setGroupQuery(user?.group_number);
  const [codeAutogenerated, setCodeAutogenerated] = useState(false);
  const {isLoading, error, mutate, data} = updateGroupQuery();
  const [isLoadingForm, setIsLoadingForm] = useState(false);

  const getDevice = async () => {
    const device = await AsyncStorage.getItem('@fcmToken');
    device && setTokenPush(device);
  };

  const submitForm = () => {
    setIsLoadingForm(true);
    if (user) {
      const userExist = geUserByPhoneNumberFirebase(user.phone);
      userExist.then(querySnapshot => {
        if (querySnapshot.empty) {
          navigation.push('Login', {
            qr: true,
            data: user,
            type
          });
        } else {
          setAlertUserExist(true);
        }
        setIsLoadingForm(false);
      });
    }
  };

  const onChangeInput = (text: never, key: DataKey) => {
    const userClone = user ? {...user} : {...userFakeData};
    userClone[key] = text;
    setUser(userClone);
  };

  const searchGroup = () => {
    user && mutate(user.group_number);
  };

  const generateGroupCode = () => {
    setCodeAutogenerated(true);
    const min = Math.ceil(0);
    const max = Math.floor(configuration?.farm_random!);
    const random = Math.floor(Math.random() * (max - min) + min);
    const newCurrentUser = {...user};
    if (random === configuration?.vehicle_code) {
      generateGroupCode();
    } else {
      newCurrentUser.group_number = random.toString();
      setUser(newCurrentUser as User);
    }
  };

  useEffect(() => {
    getDevice();
    if (currentButtonAction && myCurrentLocation && tokenPush) {
      const newCurrentUser = user ? {...user} : {...userFakeData};
      newCurrentUser.administrator = true;
      newCurrentUser.created = Date.now().toString();
      newCurrentUser.date = Date.now().toString();
      newCurrentUser.address = myCurrentLocation.address
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '');
      newCurrentUser.city = myCurrentLocation.city.long_name
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '');
      newCurrentUser.departament = myCurrentLocation.state.long_name
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '');
      newCurrentUser.location = myCurrentLocation.location!;
      newCurrentUser.phone = currentButtonAction.phone;
      newCurrentUser.pay = true;
      newCurrentUser.avatar = '';
      newCurrentUser.zipcode = parseInt(myCurrentLocation.zipCode.short_name);
      newCurrentUser.devices = [{device: tokenPush, os}];
      newCurrentUser.countryCode = myCurrentLocation.country.short_name;
      newCurrentUser.type = type;
      if (type === 'vehicle' && configuration) {
        newCurrentUser.group_number = configuration.vehicle_code?.toString()!;
        newCurrentUser.group_name = t('general.vehicle');
      }
      setUser(newCurrentUser);
    }
  }, [currentButtonAction, myCurrentLocation, tokenPush]);

  useEffect(() => {
    if (type === 'vehicle' && configuration) {
      const userClone = {...user};
      userClone.group_number = configuration.vehicle_code?.toString();
    }
  }, [type, configuration]);

  useEffect(() => {
    getLocation(setMyCurrentLocation);
  }, []);

  useEffect(() => {
    if (!isLoading && data) {
      const userClone = {...user};
      if (data.data()) {
        const groupData = data.data() as Group;
        userClone.group_name = groupData.group_name;
        setUser(userClone as User);
        setTimeout(() => {
          setGroupFound(true);
          setAlertGroupFound(false);
        }, 2000);
      } else {
        setGroupFound(false);
        setAlertGroupFound(true);
        // userClone.group_name = '';
        // setUser(userClone as User);
      }
    }
  }, [data, isLoading]);

  return {
    configuration,
    myCurrentLocation,
    setMyCurrentLocation,
    currentButtonAction,
    setCurrentButtonAction,
    generateGroupCode,
    searchGroup,
    alertGroupFound,
    setAlertGroupFound,
    onChangeInput,
    groupFound,
    submitForm,
    user,
    alertUserExist,
    setAlertUserExist,
    isLoading,
    setCodeAutogenerated,
    codeAutogenerated,
    isLoadingForm
  };
};
export {adminFormHook};
